#! /bin/sh

sxhkd &
devmon &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1 &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8
bspc config top_padding 	 8
bspc config right_padding 	 8
bspc config bottom_padding	 8
bspc config left_padding 	 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on

